config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cobalt-ostrich.sh
        container: qc.acc_tasty-khaki-eel
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-taupe-angora.sh
        container: qc.doc_flabby-azure-elephant
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-corn-capybara.sh
        container: qc.doc_skinny-purple-panda
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-corn-wallaby.sh
        container: qc.doc_flaky-myrtle-alligator
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-thistle-forest.sh
        container: qc.lic_homely-firebrick-cuscus
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-viridian-cassowary.sh
        container: qc.met_snazzy-cardinal-spider
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-champagne-ibis.sh
        container: qc.sec_tacky-cerulean-octopus
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-malachite-cheetah.sh
        container: qc.sty_queasy-ochre-wasp
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-brass-jaguar.sh
        container: qc.sty_cozy-lavender-ray
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-orange-tarantula.sh
        container: qc.sty_tasty-celadon-oriole
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.messy-periwinkle-tarsier.sh
        container: qc.sty_thirsty-cerise-shark
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-chocolate-coati.sh
        container: qc.ver_stinky-chocolate-hyena
timeout: 5400
